In [186]:
import numpy as np

#### 1.1

In [187]:
a = np.arange(12, 24)

In [188]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [198]:
c = a.reshape(3, 4)
d = a.reshape(2, 6)
e = a.reshape(4, 3)
f = a.reshape(6, 2)
g = a.reshape(12, 1)

In [199]:
c = a.reshape(3, -1)
d = a.reshape(2, -1)
e = a.reshape(4, -1)
f = a.reshape(-1, 2)
g = a.reshape(-1, 1)

#### 1.2

In [211]:
a = np.random.randn(3, 4)

In [212]:
a

array([[ 0.08314554,  1.48117044,  0.26473906, -0.05322485],
       [-0.20957397,  0.71410742, -0.30817201, -1.7234592 ],
       [-1.24092309,  0.8191943 , -0.8684496 , -1.10469518]])

In [234]:
b = a.flatten()

In [235]:
b

array([ 0.08314554,  1.48117044,  0.26473906, -0.05322485, -0.20957397,
        0.71410742, -0.30817201, -1.7234592 , -1.24092309,  0.8191943 ,
       -0.8684496 , -1.10469518])

#### 1.3

In [203]:
a = np.arange(20, 0, -2)

In [204]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [230]:
b = np.arange(20, 1, -2)

In [231]:
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 1.4

In [263]:
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.concatenate((a,b),axis=0)

In [264]:
a, b

(array([[0., 0.],
        [0., 0.]]), array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [269]:
v, np.size(v)

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]), 10)

#### 1.5

In [343]:
a = np.arange(12)
a
c = a.reshape(3, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [365]:
AT = A.T
AT

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [368]:
B = AT.dot(A)
B, B.shape

(array([[ 80,  92, 104, 116],
        [ 92, 107, 122, 137],
        [104, 122, 140, 158],
        [116, 137, 158, 179]]), (4, 4))

In [369]:
B_inv = np.linalg.inv(B)
B_inv  #Singular matrix не может иметь обратной матрицы

array([[-1.36472716e+14,  2.04709074e+14,  0.00000000e+00,
        -6.82363580e+13],
       [ 2.04709074e+14, -3.42247983e+14,  7.03687442e+13,
         6.71701649e+13],
       [ 0.00000000e+00,  7.03687442e+13, -1.40737488e+14,
         7.03687442e+13],
       [-6.82363580e+13,  6.71701649e+13,  7.03687442e+13,
        -6.93025511e+13]])

#### 1.6

In [303]:
np.random.seed(42)

In [310]:
c = np.random.randint(0, 16, 16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

In [311]:
C = c.reshape(4,4)
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [348]:
D = B + C * 10
D

array([[190, 182, 154, 236],
       [202, 187, 122, 237],
       [204, 262, 230, 308],
       [226, 247, 308, 319]])

In [370]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.16542771,  0.12978956, -0.02443291,  0.04954906],
       [-0.27716134,  0.18786098,  0.00598069,  0.0597021 ],
       [-0.06185661,  0.03820261, -0.00760226,  0.02471987],
       [ 0.39152774, -0.27429626,  0.02001913, -0.10206341]])

In [373]:
np.linalg.det(D_inv) # определитель

-2.277489295800316e-07

In [374]:
np.linalg.matrix_rank(D_inv) # ранг

4

#### 1.7
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv 
остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых 
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, 
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему 
элементу матрицы C.


In [378]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[0., 1., 0., 1.],
       [0., 1., 1., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [383]:
E = D_inv
E[E == 0] = C[]
E[E == 1] = B[]
E

SyntaxError: invalid syntax (<ipython-input-383-eb84c4cb8ace>, line 2)

In [380]:
C

array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [ ]:
#### 2
Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [319]:
a = ([1, 6],
     [2, 8],
     [3, 11],
     [3, 10],
     [1, 7] 
     )
a

([1, 6], [2, 8], [3, 11], [3, 10], [1, 7])

In [323]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

#### 3
Задание 3
Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.


In [324]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### 4
Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [340]:
#a_centered_sp = np.mean(a_centered, axis=1)
a_centered_sp = a_centered[:, 0] * a_centered[:, 1]
a_centered_sp
weee = a_centered[:, 1].T
weee


array([-2.4, -0.4,  2.6,  1.6, -1.4])

## Pandas

#### Задание 1
A.	Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
B.	Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
C.	Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [375]:
import pandas as pd
import numpy as np

In [384]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                   'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [386]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                   'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                   'price':[450, 300, 350, 500, 450, 370, 290]}, columns=['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [626]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [627]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### Задание 4
A.	Создайте датафрейм authors_stat на основе информации из authors_price.
B.	В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора,
минимальная, максимальная и средняя цена на книги этого автора.

In [628]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean'])
authors_stat = authors_stat.reset_index()
authors_stat

author_name  min  max        mean
0  Островский  290  370  330.000000
1    Тургенев  300  450  366.666667
2       Чехов  450  500  475.000000

#### Задание 5
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, 
какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. Просмотрите документацию по функции pd.pivot_table 
с помощью вопросительного знака. Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.
Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",а индексами должны 
быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого 
файла датафрейм и назовите его book_info2.Удостоверьтесь, что датафреймы book_info и book_info2 идентичны


In [629]:
book_info = pd.DataFrame({'cover': ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']}, columns = ['cover'])
authors_price = pd.concat([authors_price, cover], axis=1)
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [630]:
? pd.pivot_table

In [631]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], fill_value = 0, 
                                 aggfunc="sum").reset_index().rename_axis(None, axis=1)
book_info

author_name  мягкая  твердая
0  Островский     660        0
1    Тургенев     650      450
2       Чехов       0      950

In [632]:
book_info.to_pickle('book_info.pkl')

In [633]:
loaded_book_info = pd.read_pickle('book_info.pkl')

In [634]:
loaded_book_info.equals(book_info)

True